### ISSUE TITLE
Rename `fk` command line tool to something more appropriate 

### ISSUE THREAD

**Issue by Azhng** [fantastic-kit/fantastic-kit#14]
Need to be done before 0.1.0 

Addresses https://github.com/fantastic-kit/fantastic-kit/pull/11#discussion_r249521703

cc @lpan

**Comment by arora-aman** [comment]
Save this for 1.0.0 release?

**Comment by Azhng** [comment]
Nahh gonna rename it to `fan` :wink: 
cc: @fan70m

**Comment by null-sleep** [comment]
Feature not a bug :]

**Comment by Azhng** [comment]
I guess we are not changing it any time soon. Reopen it if someone has strong feeling for it.
