### ISSUE TITLE
Don't nest boolean operators inside `unless`

### ISSUE THREAD

**Issue by 9at8** [fantastic-kit/fantastic-kit#36]
https://github.com/fantastic-kit/fantastic-kit/blob/master/bin/fk.rb#L8

https://github.com/fantastic-kit/fantastic-kit/blob/master/bin/fk.rb#L15

This line nests a boolean operator `&&` inside an unless. Unless means 'if not', and the whole thing can become pretty confusing if you try to think about it. This should be avoided at all costs.

**Comment by 9at8** [comment]
cc: @Azhng

**Comment by Azhng** [comment]
Closed since no longer relevant
