### ISSUE TITLE
ZSH Dockerfile is outdated

### ISSUE THREAD

**Issue by arora-aman** [fantastic-kit/fantastic-kit#43]
The current Dockerfile relies on oh-my-zsh to install zsh. 

Somewhere around April/June oh-my-zsh decided to make users install zsh than them doing it. The docker file needs to be updated to support this.

Solution should be simple. More info https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH

**Comment by arora-aman** [comment]
cc: @Azhng

**Comment by Azhng** [comment]
Ack. Will take a look once I'm back to Canada.

**Comment by Azhng** [comment]
Wait just double check the Dockerfile, it's pulling zsh image directly instead of using `oh-my-zsh` to install zsh. I think it should still works.
